services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: saasbase:0.1.0
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SAASBASE_DATASOURCE_HOST: ${SAASBASE_DATASOURCE_HOST}
      SAASBASE_DATASOURCE_USERNAME: ${SAASBASE_DATASOURCE_USERNAME}
      SAASBASE_DATASOURCE_PASSWORD: ${SAASBASE_DATASOURCE_PASSWORD}
      SAASBASE_REDIS_HOST: ${SAASBASE_REDIS_HOST}
      SAASBASE_REDIS_PORT: ${SAASBASE_REDIS_PORT:-6379}
      SAASBASE_REDIS_PASSWORD: ${SAASBASE_REDIS_PASSWORD:-}
      SAASBASE_JWT_SECRET: ${SAASBASE_JWT_SECRET}
    ports:
      - "8080:8080"
